name: PHP Syntax Check

on:
  push:
    branches: [ main, master ]
    paths:
      - '**.php'
  pull_request:
    branches: [ main, master ]
    paths:
      - '**.php'

jobs:
  php-syntax-check:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php-version: ['8.0', '8.1', '8.2']

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup PHP ${{ matrix.php-version }}
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php-version }}
        extensions: mbstring, xml, ctype, iconv, intl

    - name: Check PHP syntax
      run: |
        echo "🔍 Checking PHP syntax for version ${{ matrix.php-version }}"
        find . -name "*.php" -not -path "./vendor/*" -exec php -l {} \; | tee syntax-check.log
        
        # Check if there are any syntax errors
        if grep -q "Parse error\|Fatal error\|syntax error" syntax-check.log; then
          echo "❌ PHP syntax errors found!"
          exit 1
        else
          echo "✅ No PHP syntax errors found"
        fi

    - name: Upload syntax check results
      if: failure()
      uses: actions/upload-artifact@v3
      with:
        name: syntax-errors-php${{ matrix.php-version }}
        path: syntax-check.log
