# Premier workflow : Vérification syntaxe PHP
# Ce workflow vérifie que tous les fichiers PHP ont une syntaxe correcte

name: 🔍 Vérification syntaxe PHP

# Quand ce workflow se déclenche
on:
  push:              # À chaque push
  pull_request:      # À chaque pull request
  workflow_dispatch: # Permet de lancer manuellement depuis GitHub

# Les tâches à exécuter
jobs:
  # Nom du job
  syntax-check:
    # Sur quelle machine virtuelle exécuter
    runs-on: ubuntu-latest
    
    # Les étapes du job
    steps:
      # Étape 1 : Récupérer le code du dépôt
      - name: 📥 Récupérer le code
        uses: actions/checkout@v4
        
      # Étape 2 : Installer PHP
      - name: 🐘 Installer PHP 8.3
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          
      # Étape 3 : Vérifier la syntaxe des fichiers PHP
      - name: ✅ Vérifier syntaxe PHP
        run: |
          echo "🔍 Vérification des fichiers PHP..."
          # Trouve tous les fichiers .php et vérifie leur syntaxe
          find . -name "*.php" -not -path "./vendor/*" | while read file; do
            echo "Vérification de $file"
            php -l "$file"
          done
          echo "✅ Tous les fichiers PHP ont une syntaxe correcte !"
